### ISSUE TITLE
[FEATURE] Use known info for Start/stop commands

### ISSUE THREAD

**Issue by SlimeDog** [stijnb1234/V10Lift2#29]
**Describe the bug**
Start and stop should use context to determine appropriate actions:
- If the player is in an elevator, the elevator name is known from the location.
- If the player is in an elevator, the target floor is known from the sign.
In this case, the only command required should be
> v10lift start
> v10lift stop

**Spigot version (use /version):**
1.15.2

**Plugin version (use /v10lift info), NOT LATEST!!!**
0.5.2

**Comment by stijnb1234** [comment]
> If the player is in an elevator, the elevator name is known from the location.
This is not possible, because it is not possible to find the elevator name from the location, because you only add the cab floor, and not the whole cab.

**Comment by SlimeDog** [comment]
I am standing on the cab floor. :)

**Comment by stijnb1234** [comment]
Yes, I know. But it's not safe to assume that you are always standing on the cab floor.

What I can do though, is check if the block below is from the lift, and if not so, it will return an error.

**Comment by SlimeDog** [comment]
If the button is part of the cab, and within one block of the sign, all the necessary data are known.

**Comment by SlimeDog** [comment]
Looks good. I will test when released.

**Comment by stijnb1234** [comment]
The snapshot is now available: [v0.5.3-SNAPSHOT](https://github.com/stijnb1234/V10Lift2/releases/tag/v0.5.3-SNAPSHOT)

**Comment by SlimeDog** [comment]
Works great! Thank you. We now have CommandSigns buttons adjacent to the floor-selection sign. Thanks to the start command, the elevator works even in Adventure mode.
