### ISSUE TITLE
[BUG] Lift signs not working after changing text

### ISSUE THREAD

**Issue by stijnb1234** [stijnb1234/V10Lift2#51]
**Describe the bug**
If you change the sign text in the config, the existing lifts get broken and new ones also won't work. 

**To Reproduce**
1. Change sign text in config
2. Create lift
3. It won't move or react to interaction 

**Expected behavior**
The lift should just work.

**Comment by lifehome** [comment]
![image](https://user-images.githubusercontent.com/1886237/88880504-7c752700-d25f-11ea-8b18-b9d00171eaea.png)
Also the sign doesn't support unicode text. It turns into question marks when it changes the text on the sign.
